### ISSUE TITLE
Installing simplejson kills pip on anaconda

### ISSUE THREAD

**Issue by scjody** [plotly/python-api#197]
@theengineear, from: http://stackoverflow.com/questions/28751216/plotly-killed-my-python-install?nah=1#28754036

Python 3.4 on Windows via Anaconda 2.1.0: installing simplejson (which is pulled in by Plotly's requirements.txt) kills pip:
```
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\pip-script.py", line 3, in <module>
    from pip import main
  File "C:\Anaconda3\lib\site-packages\pip\__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Anaconda3\lib\site-packages\pip\download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\compat.py", line 77, in <module>
    import simplejson as json
  File "C:\Anaconda3\lib\site-packages\simplejson\__init__.py", line 112, in <module>
    from .scanner import JSONDecodeError
  File "C:\Anaconda3\lib\site-packages\simplejson\scanner.py", line 10, in <module>
    c_make_scanner = _import_c_make_scanner()
  File "C:\Anaconda3\lib\site-packages\simplejson\scanner.py", line 6, in _import_c_make_scanner
    from simplejson._speedups import make_scanner
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte
```

Can we *not* install simplejson unless it's really needed (Python 2.6 systems)?  Or is there another way we can work around this Anaconda issue?  (Logged for Anaconda as: https://github.com/ContinuumIO/anaconda-issues/issues/238 )

**Comment by theengineear** [comment]
Ah, bummer. Yeah, we wanted to unify the install process. Do you know of a way to have pip optionally install something depending on the python version?

**Comment by theengineear** [comment]
@scjody , I think a good non-hacky workaround is to allow installing like this:

pip install plolty[PY2.6]

http://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

Then, we can just check and shoot out a warning explaining that.

**Comment by scjody** [comment]
Great idea!
